### ISSUE TITLE
RuntimeError: inverse_cpu: U(18,18) is zero, singular U.

### ISSUE THREAD

**Issue by 0h-n0** [0h-n0/thdbonas#1]
When n_trials is big, the above error is throwed.
the detail is the follwoing.
```
Traceback (most recent call last):
  File "dngo_2d_ackley_function.py", line 31, in <module>
    model_kwargs=model_kwargs)
  File "/home/ono/misc/thdbonas/thdbonas/searcher.py", line 37, in search
    self.result = optimizer.run(objective, n_trials, **kwargs)
  File "/home/ono/misc/thdbonas/thdbonas/optimizer.py", line 40, in run
    model_kwargs)
  File "/home/ono/misc/thdbonas/thdbonas/optimizer.py", line 77, in _bayes_search
    n_features)
  File "/home/ono/misc/thdbonas/thdbonas/optimizer.py", line 125, in _update_mll_params
    args=(bases, y_values, n_samples, n_features))
  File "/home/ono/.miniconda/envs/dnn/lib/python3.7/site-packages/scipy/optimize/optimize.py", line 443, in fmin
    res = _minimize_neldermead(func, x0, args, callback=callback, **opts)
  File "/home/ono/.miniconda/envs/dnn/lib/python3.7/site-packages/scipy/optimize/optimize.py", line 602, in _minimize_neldermead
    fxr = func(xr)
  File "/home/ono/.miniconda/envs/dnn/lib/python3.7/site-packages/scipy/optimize/optimize.py", line 327, in function_wrapper
    return function(*(wrapper_args + args))
  File "/home/ono/misc/thdbonas/thdbonas/optimizer.py", line 147, in _calc_marginal_log_likelihood
    k_inv = torch.inverse(k_mat)
```

**Comment by 0h-n0** [comment]
I have two options.
 * add small value to k_mat before caluculating k_inv.
* use pinv (numpy.linalg.pinv)

**Comment by 0h-n0** [comment]
The first one dose not work well.
